language: c
before_install:
  - sudo apt-get install -yy qemu-system-mips expect python3-pip
  - sudo pip3 install pyserial
  - curl -sc /tmp/gcokie 'https://drive.google.com/uc?export=download&id=1Mo5hGcCg1zm8Ca0KQB-G5PNI3fXfAAmR'
  - getcode="$(awk '/_warning_/ {print $NF}' /tmp/gcokie)"
  - curl -s -C - -LOJb /tmp/gcokie "https://drive.google.com/uc?export=download&confirm=${getcode}&id=1Mo5hGcCg1zm8Ca0KQB-G5PNI3fXfAAmR"
  - tar -xf Codescape.GNU.Tools.Package.2016.05-06.for.MIPS.MTI.Bare.Metal.CentOS-5.x86_64.tar.gz
script:
  - export PATH=$PATH:$PWD/mips-mti-elf/2016.05-06/bin
  - make GCCPREFIX=mips-mti-elf- ON_FPGA=y -C kernel/
  - |
    if [[ -n "$TRAVIS_TAG" ]]; then
      mkdir -p "$TRAVIS_TAG/kernel"
      cp kernel/kernel.bin "$TRAVIS_TAG/kernel/kernel-fpga.bin"
      cp kernel/kernel.elf "$TRAVIS_TAG/kernel/kernel-fpga.elf"
    fi 
  - make GCCPREFIX=mips-mti-elf- ON_FPGA=n EN_INT=y EN_TLB=y -C kernel/
  - |
    if [[ -n "$TRAVIS_TAG" ]]; then
      cp kernel/kernel.elf "$TRAVIS_TAG/kernel/kernel-qemu-int-tlb.elf"
      find "$TRAVIS_TAG"
    fi
  - travis_wait 1 make EN_INT=y EN_TLB=y sim -C kernel || true
  - "./.test-script"
addons:
  apt:
    update: true
deploy:
  on:
    tags: true
  provider: bintray
  user: z4yx
  skip_cleanup: true
  file: .bintray.json
  key:
    secure: GsCsdMBdTW8ZGFsRUX2Dwu11XeVEOh58gZpgelBIv/h6/6R6Zlqn/+qBVKIA6O62MKDU61DxPoQ9dhRseNY13hYLPxY/clNu4wYSGnlBEnumHPa7AnmYjYTQQyIWseVJALnZtnMhTmaStvS1zKLb0pxPdWLF8LbQA7UvZiBwOC2Kx+gVnm22Gx6LjI1dTflQUt5CnWooRbpIA2KFPXLOV+3TSaECUinHC6Gwf9ts9mpBrOpBTKNbJbkgQ3GRCNOsv73BfNq2e+KvMwEhbdPzToJ2CPRYQUyquYUuLuQ+X6dbWQfWsnIlEuktO/UpPaxopPrBQHKOvfOPnHFB9OySieJ35fKx432TDTc8RSma8aBRa+4V9FoxGj4t4By10xBWzDPWTC+mWkMCSQ7RczaOZPT3nauipDaDdi2nIvlBodJ41dS9x70/Da81Z8Nv0ZuLQ8MwXXRxfMU8Htf4KaD7Zowm37IvcoD1kbQJIkOGeSUrirMKoztzMpwDhVFbxQvKEJ7O4du5eZlibe0g2lzWSY9xlhy5n0ztjBpcP3N1SvSgKycCPIqIe/X2FzhF0szmWy9xBygQtA2cMB+dTalEuoxCw6zCK3qD4SpQKX6tY2RtaZZqXADA14+KdqowL9yLAilJ2OmuTxqszk4rEAZxs7KyU5TF8Hi3NfiGhRm+wgw=
